import { FastifyInstance } from 'fastify';
import { apiRoutes } from '@kudi/api-contracts';
import { AdminController } from './admin.controller';
import { requireAdmin } from '../../utils/authGuards';

export async function adminRoutes(server: FastifyInstance, controller: AdminController) {
  server.get(apiRoutes.rates.current, controller.getCurrentRates);
  server.get('/api/rates/current', controller.getCurrentRates);
  server.get('/api/v1/admin/dashboard', { preHandler: requireAdmin }, controller.getDashboard);
  server.get('/api/admin/dashboard', { preHandler: requireAdmin }, controller.getDashboard);
  server.get('/api/v1/admin/users', { preHandler: requireAdmin }, controller.getUsers);
  server.get('/api/admin/users', { preHandler: requireAdmin }, controller.getUsers);
  server.get('/api/v1/admin/transactions', { preHandler: requireAdmin }, controller.getTransactions);
  server.get('/api/admin/transactions', { preHandler: requireAdmin }, controller.getTransactions);
  server.post(apiRoutes.admin.rateOverride, { preHandler: requireAdmin }, controller.overrideRate);
  server.post('/api/admin/rate-override', { preHandler: requireAdmin }, controller.overrideRate);
  server.get(apiRoutes.admin.config, { preHandler: requireAdmin }, controller.getConfig);
  server.get('/api/admin/config', { preHandler: requireAdmin }, controller.getConfig);
  server.get(apiRoutes.admin.maintenance, { preHandler: requireAdmin }, controller.getMaintenanceConfig);
  server.get('/api/admin/config/maintenance', { preHandler: requireAdmin }, controller.getMaintenanceConfig);
  server.get('/api/v1/admin/config/maintenance', { preHandler: requireAdmin }, controller.getMaintenanceConfig);
  server.post(apiRoutes.admin.maintenance, { preHandler: requireAdmin }, controller.setMaintenanceConfig);
  server.post('/api/admin/config/maintenance', { preHandler: requireAdmin }, controller.setMaintenanceConfig);
  server.post('/api/v1/admin/config/maintenance', { preHandler: requireAdmin }, controller.setMaintenanceConfig);
  server.get('/api/v1/admin/deposits', { preHandler: requireAdmin }, controller.getDeposits);
  server.get('/api/admin/deposits', { preHandler: requireAdmin }, controller.getDeposits);
  server.get('/api/v1/admin/sweeps/health', { preHandler: requireAdmin }, controller.getSweepHealth);
  server.get('/api/admin/sweeps/health', { preHandler: requireAdmin }, controller.getSweepHealth);
  server.get('/api/v1/admin/operator-alerts', { preHandler: requireAdmin }, controller.getOperatorAlerts);
  server.get('/api/admin/operator-alerts', { preHandler: requireAdmin }, controller.getOperatorAlerts);
  server.post('/api/v1/admin/sweeps/:signature/requeue', { preHandler: requireAdmin }, controller.requeueSweep);
  server.post('/api/admin/sweeps/:signature/requeue', { preHandler: requireAdmin }, controller.requeueSweep);
  server.post('/api/v1/admin/sweeps/:signature/recheck', { preHandler: requireAdmin }, controller.recheckSweep);
  server.post('/api/admin/sweeps/:signature/recheck', { preHandler: requireAdmin }, controller.recheckSweep);
  server.post(apiRoutes.admin.setActiveProvider, { preHandler: requireAdmin }, controller.setActiveProvider);
  server.post('/api/admin/set-active-provider', { preHandler: requireAdmin }, controller.setActiveProvider);
  server.get('/api/v1/admin/rails', { preHandler: requireAdmin }, controller.getPayoutRails);
  server.get('/api/admin/rails', { preHandler: requireAdmin }, controller.getPayoutRails);
  server.get(apiRoutes.admin.exportReconciliationCsv, { preHandler: requireAdmin }, controller.exportReconciliationCSV);
  server.get('/api/admin/reconciliation/export-csv', { preHandler: requireAdmin }, controller.exportReconciliationCSV);
}
